# Generated by Django 5.1.3 on 2024-12-04 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calories', models.PositiveIntegerField(default=2000, help_text='Daily calorie goal in kcal.')),
                ('protein', models.PositiveIntegerField(default=50, help_text='Daily protein goal in grams.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Last updated timestamp.')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daily_goal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
