# Generated by Django 5.1.3 on 2024-12-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiondata',
            name='class_name',
            field=models.CharField(default='Food name', max_length=100),
            preserve_default=False,
        ),
    ]
