# Generated by Django 5.1.3 on 2024-12-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailygoal',
            name='carbs',
            field=models.PositiveIntegerField(default=250, help_text='Daily carbohydrate goal in grams.'),
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='fats',
            field=models.PositiveIntegerField(default=70, help_text='Daily fat goal in grams.'),
        ),
    ]
