# Generated by Django 5.1.3 on 2024-12-20 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0002_nutritiondata_class_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiondata',
            name='iron',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
