# Generated by Django 5.1.3 on 2024-12-20 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0003_nutritiondata_iron'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiondata',
            name='calcium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritiondata',
            name='sodium',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
