# Generated by Django 5.1.3 on 2024-12-20 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0004_nutritiondata_calcium_nutritiondata_sodium'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiondata',
            name='folic_acid',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritiondata',
            name='magnesium',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritiondata',
            name='phosphorus',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
