# Generated by Django 5.1.3 on 2024-12-20 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0005_nutritiondata_folic_acid_nutritiondata_magnesium_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiondata',
            name='cholestrol',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritiondata',
            name='vitaminb12',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='nutritiondata',
            name='zinc',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
