# Generated by Django 5.1.3 on 2024-12-26 00:56

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0006_nutritiondata_cholestrol_nutritiondata_vitaminb12_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutritiondata',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
