# Generated by Django 5.1.3 on 2024-12-25 14:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calorie', '0006_nutritiondata_cholestrol_nutritiondata_vitaminb12_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailygoal',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='height',
            field=models.DecimalField(decimal_places=2, default=170, max_digits=5),
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='lifestyle',
            field=models.CharField(choices=[('S', 'Sedentary'), ('M', 'Moderately Active'), ('A', 'Active'), ('V', 'Very Active')], default='S', max_length=1),
        ),
        migrations.AddField(
            model_name='dailygoal',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=70, max_digits=5),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='calories',
            field=models.PositiveIntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='carbs',
            field=models.PositiveIntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='fats',
            field=models.PositiveIntegerField(default=67),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='protein',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='dailygoal',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
