# Generated by Django 5.1.3 on 2024-12-25 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='calorie_goal',
            field=models.IntegerField(default=2000),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='nutrient_goal',
            field=models.TextField(default=''),
        ),
    ]
